# Generated by Django 4.2.3 on 2023-07-31 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dirección', models.CharField(max_length=50)),
                ('teléfono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehículo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
                ('foto', models.ImageField(null=True, upload_to='vehículos')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('costo', models.FloatField(verbose_name='Costo del vehículo')),
                ('observaciones', models.CharField(max_length=50)),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('vehículo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.vehículo')),
            ],
        ),
    ]
