# Generated by Django 4.2.3 on 2023-07-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.FloatField(choices=[(0.1, '10%'), (0.2, '20%'), (0.3, '30%')]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.FloatField(choices=[(0.12, '12%')]),
        ),
    ]
