# Generated by Django 4.2.3 on 2023-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('anio', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('foto', models.ImageField(null=True, upload_to='vehiculos')),
            ],
        ),
    ]
