# Generated by Django 4.2.3 on 2023-07-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_total_alter_venta_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehículo',
            name='tipo',
        ),
    ]
