# Generated by Django 4.2.3 on 2023-07-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('costo', models.FloatField(verbose_name='Costo del vehiculo')),
                ('observaciones', models.CharField(max_length=50)),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.vehiculo')),
            ],
        ),
    ]
