# Generated by Django 4.2.3 on 2023-07-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cliente_telefono_alter_vehiculo_anio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
